from enum import Enum


class ResponseType(Enum):
    MESSAGE = 'MESSAGE'
    ACTION_BAN = 'ACTION_BAN'
    ACTION_TIMEOUT = 'ACTION_TIMEOUT'
    ACTION_UNBAN = 'ACTION_UNBAN'
    ACTION_JOIN = 'ACTION_JOIN'
    ACTION_LEAVE = 'ACTION_LEAVE'
    MODE_SLOW = 'MODE_SLOW'
    MODE_SLOW_OFF = 'MODE_SLOW_OFF'
    MODE_SUB = 'MODE_SUB'
    MODE_SUB_OFF = 'MODE_SUB_OFF'
    MODE_EMOTE = 'MODE_EMOTE'
    MODE_EMOTE_OFF = 'MODE_EMOTE_OFF'
    MODE_FOLLOW = 'MODE_FOLLOW'
    MODE_FOLLOW_OFF = 'MODE_FOLLOW_OFF'
    UPDATE_MOD_STA = 'UPDATE_MOD_STA'
