from enum import Enum


class System(Enum):
    KRYABOT_TELEGRAM = 'KRYABOT_TELEGRAM'
    KRYABOT_TWITCH = 'KRYABOT_TWITCH'
    KRYABOT_SPAM_DETECTOR = 'KRYABOT_SPAM_DETECTOR'
    KRYABOT_TMI = 'KRYABOT_TMI'
    AUTHBOT_TELEGRAM = 'AUTHBOT_TELEGRAM'
    INFOBOT_TELEGRAM = 'INFOBOT_TELEGRAM'
    INFOMANAGER = 'INFOMANAGER'
    WEBSERVER = 'WEBSERVER'
    API = 'API'
