# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USERNAME, $DOCKERHUB_PASSWORD setup as deployment variables

image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          script:
            - IMAGE_NAME=oskaras/kryabot:latest
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - docker push "${IMAGE_NAME}"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
