from tgbot.commands.actions.AddBan import AddBan
from tgbot.commands.actions.AddVip import AddVip
from tgbot.commands.actions.Unlist import Unlist
from tgbot.commands.actions.Next import Next
from tgbot.commands.actions.Invite import Invite
from tgbot.commands.actions.ShowNonVerifiedList import ShowNonVerifiedList
from tgbot.commands.actions.Whois import Whois
from tgbot.commands.actions.Whoami import Whoami
from tgbot.commands.actions.MassMessage import MassMessage
from tgbot.commands.actions.SetLang import SetLang
from tgbot.commands.actions.ReloadTranslations import ReloadTranslations
from tgbot.commands.actions.ReloadWords import ReloadWords
from tgbot.commands.actions.UserReport import UserReport
from tgbot.commands.actions.SetMyInst import SetMyInst
from tgbot.commands.actions.SetMyVk import SetMyVk
from tgbot.commands.actions.SetMyUt import SetMyUt
from tgbot.commands.actions.GetMessageDetails import GetMessageDetails
from tgbot.commands.actions.GlobalUserReport import GlobalUserReport
from tgbot.commands.actions.SubHistory import SubHistory
from tgbot.commands.actions.AddHelper import AddHelper
from tgbot.commands.actions.SpeedTest import SpeedTest
from tgbot.commands.actions.DLCoub import DLCoub
from tgbot.commands.actions.SpawnBoss import SpawnBoss
from tgbot.commands.actions.SpawnBox import SpawnBox
from tgbot.commands.actions.SpawnLove import SpawnLove
from tgbot.commands.actions.SpawnNumber import SpawnNumber
from tgbot.commands.actions.SpawnSilent import SpawnSilent
from tgbot.commands.actions.SpawnScary import SpawnScary
from tgbot.commands.actions.SpawnGreedy import SpawnGreedy
from tgbot.commands.actions.SpawnSnowing import SpawnSnowing
from tgbot.commands.actions.NewUserReport import NewUserReport
from tgbot.commands.actions.DryMassKick import DryMassKick
