from tgbot.commands.actions.AddBan import AddBan
from tgbot.commands.actions.AddVip import AddVip
from tgbot.commands.actions.Unlist import Unlist
from tgbot.commands.actions.Next import Next
from tgbot.commands.actions.Invite import Invite
from tgbot.commands.actions.ShowNonVerifiedList import ShowNonVerifiedList
from tgbot.commands.actions.Whois import Whois
from tgbot.commands.actions.Whoami import Whoami
from tgbot.commands.actions.SetLang import SetLang
from tgbot.commands.actions.SetMyInst import SetMyInst
from tgbot.commands.actions.SetMyVk import SetMyVk
from tgbot.commands.actions.SetMyUt import SetMyUt
from tgbot.commands.actions.GetMessageDetails import GetMessageDetails
from tgbot.commands.actions.SubHistory import SubHistory
from tgbot.commands.actions.AddHelper import AddHelper
from tgbot.commands.actions.DLCoub import DLCoub
from tgbot.commands.actions.Random import Random
